---
# jenkins related tasks file for jenkins_server

- name: Push jenkins conf
  sudo: yes
  copy:
    src=jenkins.conf
    dest=/etc/default/jenkins
    mode=0644

- name: Configure jenkins
  sudo: yes
  template:
    src=jenkins_config.xml.j2
    dest=/var/lib/jenkins/config.xml
  notify:
    - 'Restart Jenkins'

- name: Configure jenkins location
  sudo: yes
  template:
    src=jenkins_location.xml.j2
    dest=/var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
  notify:
    - 'Restart Jenkins'

- name: Configure jenkins theme
  sudo: yes
  template:
    src=jenkins_simple_theme.xml.j2
    dest=/var/lib/jenkins/org.codefirst.SimpleThemeDecorator.xml
  notify:
    - 'Restart Jenkins'

# false in slave-to-master-switch means that is enabled
- name: Enable security between nodes and master
  sudo: yes
  copy:
    src=slave-to-master-switch
    dest=/var/lib/jenkins/secrets/slave-to-master-security-kill-switch

- name: Whitelist paths for node -> master connection
  sudo: yes
  copy:
    src=slave-to-master-control.conf
    dest=/var/lib/jenkins/secrets/filepath-filters.d/50-gui.conf
