---
# tasks file for jenkins_server

- name: Update
  apt: update_cache=yes

- name: Install dependencies
  sudo: yes
  apt: name={{ item }} state=installed
  with_items:
    - nginx

- name: Push jenkins conf
  copy: src=jenkins.conf dest=/etc/default/jenkins mode=0644

- name: Configure jenkins
  template: src=jenkins_config.xml.j2 dest=/var/lib/jenkins/config.xml
  notify:
    - 'Restart Jenkins'

- name: Upload nginx.conf
  action: copy src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Upload nginx vhost template
  template: src=jenkins_vhost.conf.j2 dest=/etc/nginx/sites-available/jenkins_vhost.conf owner=root group=root mode=0755

- name: Create the link for site enabled specific configurations
  file: path=/etc/nginx/sites-enabled/jenkins_vhost.conf state=link src=/etc/nginx/sites-available/jenkins_vhost.conf

- name: Deactivate the default nginx site
  file: path=/etc/nginx/sites-enabled/default
          state=absent
  notify: restart nginx
