---
# tasks file for jenkins_server

# Todo:Run update

- name: Add jenkins apt-key
  sudo: yes
  apt_key: url={{ jenkins.deb.key }} state=present

- name: Add Jenkins repository
  sudo: yes
  apt_repository: repo={{ jenkins.deb.repo }} state=present

- name: Install dependencies
  sudo: yes
  apt: name {{ items }} state=installed
  with_items:
    - jenkins

# Todo: install jenkins plugins
# Todo: install nginx
# Todo: setup nginx site
