---
# nginx related tasks file for jenkins_server

- name: Create SSL certificates folder
  become: yes
  file:
    path=/etc/nginx/ssl
    state=directory
    owner=root
    group=root

- name: SSL | upload SSL certificate key
  become: yes
  copy:
    content: '{{ ssl_key_data }}'
    dest: /etc/nginx/ssl/cert.key
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: SSL | upload SSL certificate
  become: yes
  copy:
    content: '{{ ssl_certificate_data }}'
    dest: /etc/nginx/ssl/cert.crt
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Upload nginx.conf
  become: yes
  copy:
    src=nginx.conf
    dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Upload nginx vhost template
  become: yes
  template:
    src=jenkins_vhost.conf.j2
    dest=/etc/nginx/sites-available/jenkins_vhost.conf
    owner=root
    group=root
    mode=0755
  notify: restart nginx

- name: Create the link for site enabled specific configurations
  become: yes
  file:
    path=/etc/nginx/sites-enabled/jenkins_vhost.conf
    state=link
    src=/etc/nginx/sites-available/jenkins_vhost.conf
  notify: restart nginx

- name: Deactivate the default nginx site
  become: yes
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify: restart nginx
